const types = {
  UPDATE_USER: '@app/UPDATE_USER',
  UPDATE_PAYMENT_METHOD: '@app/UPDATE_PAYMENT_METHOD',
  UPDATE_CAR: '@app/UPDATE_CAR',
  CHECK_USER: '@app/CHECK_USER',
  CREATE_USER: '@app/CREATE_USER',
  GET_RIDE_INFOS: '@app/GET_RIDE_INFOS',
  UPDATE_RIDE: '@app/UPDATE_RIDE',
  REQUEST_RIDE: '@app/REQUEST_RIDE',
  ACCEPT_RIDE: '@app/ACCEPT_RIDE',
};

export default types;
